import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Inter } from 'next/font/google';

const interfont = Inter({
  subsets: ['latin'],
  weight: ['400'],
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: "400"
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${interfont.className} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
